"""Native Python Bridge for Adobe Lightroom Classic.

Communicates with Lightroom Classic via dual TCP sockets (Request on 58763, Response on 58764)
using JSON-RPC style payloads authenticated with token at ~/.config/lightroom-mcp/token.
Includes robust error handling, auto-reconnect, and timeouts.
"""

from __future__ import annotations

import json
import os
import socket
import time
import uuid
from typing import Any


class LightroomBridge:
    def __init__(
        self,
        request_port: int = 58763,
        response_port: int = 58764,
        auth_file_path: str = "~/.config/lightroom-mcp/token",
        timeout: float = 15.0
    ):
        self.request_port = request_port
        self.response_port = response_port
        self.auth_file_path = os.path.expanduser(auth_file_path)
        self.timeout = timeout

    def get_token(self) -> str:
        """Reads authentication token generated by Lightroom Classic plugin."""
        if not os.path.exists(self.auth_file_path):
            raise FileNotFoundError(
                f"Lightroom MCP token not found at {self.auth_file_path}. "
                "Ensure Adobe Lightroom Classic is running and LightroomMCP plugin is enabled."
            )
        with open(self.auth_file_path, encoding="utf-8") as f:
            return f.read().strip()

    def _connect_response_socket(self) -> socket.socket:
        resp_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        resp_sock.settimeout(self.timeout)
        try:
            resp_sock.connect(("localhost", self.response_port))
            return resp_sock
        except (TimeoutError, ConnectionRefusedError) as e:
            resp_sock.close()
            raise ConnectionError(
                f"Failed to connect to Lightroom response port {self.response_port}: {e}. "
                "Ensure Lightroom Classic is open and plugin is listening."
            ) from e

    def _send_request(self, payload: dict[str, Any]) -> None:
        req_sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        req_sock.settimeout(self.timeout)
        try:
            req_sock.connect(("localhost", self.request_port))
            data_bytes = (json.dumps(payload) + "\n").encode("utf-8")
            req_sock.sendall(data_bytes)
        except Exception as e:
            raise ConnectionError(f"Failed to send request to Lightroom on port {self.request_port}: {e}") from e
        finally:
            req_sock.close()

    def _read_response(self, resp_sock: socket.socket, req_id: str, action: str) -> Any:
        buffer = ""
        start_time = time.time()
        while time.time() - start_time < self.timeout:
            chunk = resp_sock.recv(4096).decode("utf-8", errors="ignore")
            if not chunk:
                break
            buffer += chunk
            if "\n" in buffer:
                line = buffer.split("\n", 1)[0].strip()
                if not line:
                    continue
                parsed = json.loads(line)
                if parsed.get("id") == req_id:
                    if parsed.get("error"):
                        raise RuntimeError(f"Lightroom error: {parsed['error']}")
                    return parsed.get("result")
        raise TimeoutError(f"Timed out waiting for Lightroom response to action '{action}'")

    def execute(self, action: str, params: dict[str, Any] | None = None) -> Any:
        """Executes an action on Lightroom Classic via dual sockets and waits for response."""
        token = self.get_token()
        req_id = str(uuid.uuid4())
        payload = {
            "id": req_id,
            "action": action,
            "hello": token,
            "params": params or {}
        }

        resp_sock = self._connect_response_socket()
        try:
            self._send_request(payload)
            return self._read_response(resp_sock, req_id, action)
        finally:
            resp_sock.close()


# Singleton bridge instance
bridge = LightroomBridge()
